### ISSUE TITLE
missing collider

### ISSUE THREAD

**Issue by dipth** [dipth/flatten_the_curve#1]
![Capture](https://user-images.githubusercontent.com/171490/87225926-c66d9a00-c390-11ea-9c25-885ec2df2a85.JPG)

**Comment by PierreNS** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GitTest](https://trello.com/c/5BZmBon9/16-gittest)

**Comment by PierreNS** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Win 10 home vs pro](https://trello.com/c/tKWKdoSH/1-win-10-home-vs-pro)
